### ISSUE TITLE
your session-based bots are quite complicated

### ISSUE THREAD

**Issue by tuanteku9x** [Widiskel/popp-to-the-moon-bot#2]
In general, your session-based bots are quite complicated.
Creating a session with a phone number the first time is mandatory, ok, then when running the bot, I have to add the phone number again,...
I have created 3 different sessions but when running again, the 3 processes are the same session?.

![2024-08-05 07_43_05-Widiskel_popp-to-the-moon-bot_ Popp to the mon bot is bot for auto farm, it help](https://github.com/user-attachments/assets/2b8d2f7b-3ab2-4a35-83eb-5970dcaea03b)

**Comment by Widiskel** [comment]
for me its not im just creating session > add phone > verif > season created (usually after created im terminate bot using ctrl+c) and start again, after that im start bot with option 3.

the advantage using my session is after you created session for 1 bot, you can use it to another bot by just copy paste session folder

and if you do it wrong when creating session you can just delete session > session name folder actually, don't need to reset

**Comment by tuanteku9x** [comment]
After created 3 session, then select 3 to run bot, it's ask phone number again!!!??

Lets getting started.
Your Session List:
- 3322
- bae
- duyen

Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : 3
[2024-08-05T10:28:35.844] [INFO] - [Running gramJS version 2.22.1]
[2024-08-05T10:28:35.913] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-08-05T10:28:38.288] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-08-05T10:28:38.312] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Phone Number ? +840382377264
[2024-08-05T10:31:38.420] [INFO] - [Phone migrated to 5]
[2024-08-05T10:31:38.655] [INFO] - [Reconnecting to new data center 5]
[2024-08-05T10:31:38.973] [WARN] - [Disconnecting...]
[2024-08-05T10:31:38.973] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
[2024-08-05T10:31:38.976] [INFO] - [Connecting to 91.108.56.196:80/TCPFull...]
[2024-08-05T10:31:38.977] [INFO] - [connection closed]
[2024-08-05T10:31:40.807] [INFO] - [Connection to 91.108.56.196:80/TCPFull complete!]
[2024-08-05T10:31:40.831] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Verification Code ? 43971
? Enter your Telegram Password? 
[2024-08-05T10:31:55.351] [INFO] - [Signed in successfully as Ngoc Bae 🚀PoPP]

[2024-08-05T10:31:55.632] [WARN] - [Disconnecting...]
[2024-08-05T10:31:55.633] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]
[2024-08-05T10:31:55.633] [WARN] - [Disconnecting...]
[2024-08-05T10:31:55.633] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]
[2024-08-05T10:31:55.675] [INFO] - [Running gramJS version 2.22.1]
[2024-08-05T10:31:55.787] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-08-05T10:31:55.788] [INFO] - [connection closed]
[2024-08-05T10:31:58.395] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-08-05T10:31:58.421] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Phone Number ? [2024-08-05T10:32:01.568] [WARN] - [Disconnecting...]
[2024-08-05T10:32:01.570] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]

**Comment by Widiskel** [comment]
maybe something wrong when you create one of your session, try deleting it one by one and re create it

**Comment by tuanteku9x** [comment]
> maybe something wrong when you create one of your session, try deleting it one by one and re create it

[2024-08-10T14:18:42.566] [INFO] - [Signed in successfully as Ngoc Bae🏅️]

[2024-08-10T14:18:42.567] [WARN] - [Disconnecting...]
[2024-08-10T14:18:42.567] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]
[2024-08-10T14:18:42.568] [WARN] - [Disconnecting...]
[2024-08-10T14:18:42.569] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]
Session undefined - Created
TypeError: Helper.sleep is not a function
    at Telegram.sessionCreation (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:84:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.onBoarding (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:44:9)
    at async Telegram.init (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:19:7)
    at async file:///D:/Telebot/popp-to-the-moon-bot-master/index.js:76:9
Error During executing bot TypeError: Helper.sleep is not a function
    at Telegram.sessionCreation (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:84:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.onBoarding (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:44:9)
    at async Telegram.init (file:///D:/Telebot/popp-to-the-moon-bot-master/src/core/telegram.js:19:7)
    at async file:///D:/Telebot/popp-to-the-moon-bot-master/index.js:76:9
? Welcome to Popp Bot
By : Widiskel

Lets getting started.
Your Session List:
- bae

Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : [2024-08-10T14:18:42.576] [INFO] - [connection closed]
[2024-08-10T14:18:50.850] [WARN] - [Disconnecting...]
[2024-08-10T14:18:50.855] [INFO] - [Disconnecting from 91.108.56.196:80/TCPFull...]

**Comment by Widiskel** [comment]
ahh , it not session fault , its my code fault , ok pull new update
