### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by razak95** [Widiskel/popp-to-the-moon-bot#4]
Input your choice : 3
Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined,
    at Helper.getSession (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/utils/helper.js:84:13)
    at Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:50:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async Telegram.sessionCreation (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:85:7)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:44:9)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:52:11)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:48:9)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/index.js:79:9
Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined,
    at Helper.getSession (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/utils/helper.js:84:13)
    at Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:50:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async Telegram.sessionCreation (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:85:7)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:44:9)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:52:11)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:48:9)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/index.js:79:9
Error During executing bot Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined,
    at Helper.getSession (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/utils/helper.js:84:13)
    at Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:50:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async Telegram.sessionCreation (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:85:7)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:44:9)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:52:11)
    at async Telegram.onBoarding (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:48:9)
    at async Telegram.init (file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/src/core/telegram.js:19:7)
    at async file:///C:/Users/Administrator/Documents/Airdrop/popp/popp-to-the-moon-bot/index.js:79:9

**Comment by Widiskel** [comment]
follow setup & configuration step correctly
